/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.nhanvien;

import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.JPanel;

public class FrmNV extends javax.swing.JFrame {

    private JPanel panel;
 

    public FrmNV() {
        initComponents();
        setTitle("NHÂN VIÊN");
        setLocationRelativeTo(null);

        panel = new JplHoadon();
        setPanel(panel);
    }

//    public FrmNV(JPanel panel) {
//        setPanel(panel);
//    }
    
    private void setPanel(JComponent p) {
        Jpncontain.removeAll();
        Jpncontain.add(p);
        Jpncontain.repaint();
        Jpncontain.revalidate();
    }

    private void resetColor(JPanel p) {
        p.setBackground(new Color(0, 153, 0));
    }

    private void setColor(JPanel p) {
        p.setBackground(new Color(222, 73, 93));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnhoadon = new javax.swing.JPanel();
        lblhoadon = new javax.swing.JLabel();
        Jpnkhachhang = new javax.swing.JPanel();
        lblkhachhang = new javax.swing.JLabel();
        Jpnsanpham = new javax.swing.JPanel();
        lblsp = new javax.swing.JLabel();
        Jpncontain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(82, 83, 81));

        jPanel4.setBackground(new java.awt.Color(255, 71, 26));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ CỬA HÀNG LAPTOP");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpnhoadon.setBackground(new java.awt.Color(0, 153, 0));
        jpnhoadon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnhoadon.setForeground(new java.awt.Color(255, 255, 255));

        lblhoadon.setForeground(new java.awt.Color(255, 255, 255));
        lblhoadon.setText("Hoá đơn");
        lblhoadon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblhoadonFocusGained(evt);
            }
        });
        lblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhoadonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblhoadonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblhoadonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnhoadonLayout = new javax.swing.GroupLayout(jpnhoadon);
        jpnhoadon.setLayout(jpnhoadonLayout);
        jpnhoadonLayout.setHorizontalGroup(
            jpnhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnhoadonLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblhoadon)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jpnhoadonLayout.setVerticalGroup(
            jpnhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnhoadonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblhoadon)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Jpnkhachhang.setBackground(new java.awt.Color(0, 153, 0));
        Jpnkhachhang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Jpnkhachhang.setForeground(new java.awt.Color(255, 255, 255));

        lblkhachhang.setForeground(new java.awt.Color(255, 255, 255));
        lblkhachhang.setText("Danh sách khách hàng");
        lblkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblkhachhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblkhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblkhachhangMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JpnkhachhangLayout = new javax.swing.GroupLayout(Jpnkhachhang);
        Jpnkhachhang.setLayout(JpnkhachhangLayout);
        JpnkhachhangLayout.setHorizontalGroup(
            JpnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnkhachhangLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lblkhachhang)
                .addGap(42, 42, 42))
        );
        JpnkhachhangLayout.setVerticalGroup(
            JpnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnkhachhangLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblkhachhang)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Jpnsanpham.setBackground(new java.awt.Color(0, 153, 0));
        Jpnsanpham.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Jpnsanpham.setForeground(new java.awt.Color(255, 255, 255));

        lblsp.setForeground(new java.awt.Color(255, 255, 255));
        lblsp.setText("Tra cứu sản phẩm");
        lblsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblspMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblspMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblspMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JpnsanphamLayout = new javax.swing.GroupLayout(Jpnsanpham);
        Jpnsanpham.setLayout(JpnsanphamLayout);
        JpnsanphamLayout.setHorizontalGroup(
            JpnsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnsanphamLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblsp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpnsanphamLayout.setVerticalGroup(
            JpnsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnsanphamLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblsp)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpnhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Jpnkhachhang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jpnsanpham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jpnhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Jpnkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Jpnsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Jpncontain.setBackground(new java.awt.Color(179, 179, 179));
        Jpncontain.setOpaque(false);

        javax.swing.GroupLayout JpncontainLayout = new javax.swing.GroupLayout(Jpncontain);
        Jpncontain.setLayout(JpncontainLayout);
        JpncontainLayout.setHorizontalGroup(
            JpncontainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        JpncontainLayout.setVerticalGroup(
            JpncontainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Jpncontain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Jpncontain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void lblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonMouseClicked
        setPanel(new JplHoadon());
    }//GEN-LAST:event_lblhoadonMouseClicked

    private void lblhoadonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblhoadonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lblhoadonFocusGained

    private void lblkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkhachhangMouseClicked
        panel = new JplKhachhang();
        setPanel(panel);
    }//GEN-LAST:event_lblkhachhangMouseClicked

    private void lblspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblspMouseClicked
        panel = new JplSanpham();
        setPanel(panel);
    }//GEN-LAST:event_lblspMouseClicked

    private void lblhoadonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonMouseEntered
        setColor(jpnhoadon);
    }//GEN-LAST:event_lblhoadonMouseEntered

    private void lblkhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkhachhangMouseEntered
        setColor(Jpnkhachhang);
    }//GEN-LAST:event_lblkhachhangMouseEntered

    private void lblspMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblspMouseEntered
        setColor(Jpnsanpham);
    }//GEN-LAST:event_lblspMouseEntered

    private void lblhoadonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonMouseExited
        resetColor(jpnhoadon);
    }//GEN-LAST:event_lblhoadonMouseExited

    private void lblkhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkhachhangMouseExited
        resetColor(Jpnkhachhang);
    }//GEN-LAST:event_lblkhachhangMouseExited

    private void lblspMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblspMouseExited
        resetColor(Jpnsanpham);
    }//GEN-LAST:event_lblspMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpncontain;
    private javax.swing.JPanel Jpnkhachhang;
    private javax.swing.JPanel Jpnsanpham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpnhoadon;
    private javax.swing.JLabel lblhoadon;
    private javax.swing.JLabel lblkhachhang;
    private javax.swing.JLabel lblsp;
    // End of variables declaration//GEN-END:variables
}
