package viewquanly;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class FrmMain extends javax.swing.JFrame {

    private String dir = null;

    public FrmMain() {
        String path = "src\\main\\java\\icon\\";
        File file = new File(path);
        String absolutePath = file.getAbsolutePath();
        dir = absolutePath;

        initComponents();
        setLocationRelativeTo(null);
        setTitle("QUẢN LÝ CỬA HÀNG BÁN LAPTOP");
        ChuyenManHinh mhinh = new ChuyenManHinh(jpnview);
        mhinh.setView(jpnqldonhang, lblqldonhang);

        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("QLdonhang", jpnqldonhang, lblqldonhang));
        listItem.add(new DanhMucBean("QLnhanvien", jpnquanlynhanvien, lblquanlynhanvien));
        listItem.add(new DanhMucBean("QLkhachhang", jpnquanlykhachhang, lblquanlykhachhang));
        listItem.add(new DanhMucBean("Thongke", jpnthongke, lblthongke));
        mhinh.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnroot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnqldonhang = new javax.swing.JPanel();
        lblqldonhang = new javax.swing.JLabel();
        jpnquanlynhanvien = new javax.swing.JPanel();
        lblquanlynhanvien = new javax.swing.JLabel();
        jpnquanlykhachhang = new javax.swing.JPanel();
        lblquanlykhachhang = new javax.swing.JLabel();
        jpnthongke = new javax.swing.JPanel();
        lblthongke = new javax.swing.JLabel();
        jpnview = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(82, 83, 81));

        jPanel3.setBackground(new java.awt.Color(255, 71, 26));

        jLabel1.setIcon(new javax.swing.ImageIcon(dir+"\\store.png"));
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ CỬA HÀNG LAPTOP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jpnqldonhang.setBackground(new java.awt.Color(0, 153, 0));
        jpnqldonhang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblqldonhang.setIcon(new javax.swing.ImageIcon(dir+"\\hoadon.png"));
        lblqldonhang.setForeground(new java.awt.Color(255, 255, 255));
        lblqldonhang.setText("Quản Lý Đơn Hàng");

        javax.swing.GroupLayout jpnqldonhangLayout = new javax.swing.GroupLayout(jpnqldonhang);
        jpnqldonhang.setLayout(jpnqldonhangLayout);
        jpnqldonhangLayout.setHorizontalGroup(
            jpnqldonhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnqldonhangLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblqldonhang)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jpnqldonhangLayout.setVerticalGroup(
            jpnqldonhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnqldonhangLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblqldonhang)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnquanlynhanvien.setBackground(new java.awt.Color(0, 153, 0));
        jpnquanlynhanvien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnquanlynhanvien.setForeground(new java.awt.Color(255, 255, 255));

        lblquanlynhanvien.setIcon(new javax.swing.ImageIcon(dir+"\\infor.png"));
        lblquanlynhanvien.setForeground(new java.awt.Color(255, 255, 255));
        lblquanlynhanvien.setText("Quản Lý Nhân Viên");

        javax.swing.GroupLayout jpnquanlynhanvienLayout = new javax.swing.GroupLayout(jpnquanlynhanvien);
        jpnquanlynhanvien.setLayout(jpnquanlynhanvienLayout);
        jpnquanlynhanvienLayout.setHorizontalGroup(
            jpnquanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnquanlynhanvienLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblquanlynhanvien)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jpnquanlynhanvienLayout.setVerticalGroup(
            jpnquanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnquanlynhanvienLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblquanlynhanvien)
                .addGap(17, 17, 17))
        );

        jpnquanlykhachhang.setBackground(new java.awt.Color(0, 153, 0));
        jpnquanlykhachhang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnquanlykhachhang.setForeground(new java.awt.Color(255, 255, 255));

        lblquanlykhachhang.setIcon(new javax.swing.ImageIcon(dir+"\\infor.png"));
        lblquanlykhachhang.setForeground(new java.awt.Color(255, 255, 255));
        lblquanlykhachhang.setText("Quản Lý Khách Hàng");

        javax.swing.GroupLayout jpnquanlykhachhangLayout = new javax.swing.GroupLayout(jpnquanlykhachhang);
        jpnquanlykhachhang.setLayout(jpnquanlykhachhangLayout);
        jpnquanlykhachhangLayout.setHorizontalGroup(
            jpnquanlykhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnquanlykhachhangLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblquanlykhachhang)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jpnquanlykhachhangLayout.setVerticalGroup(
            jpnquanlykhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnquanlykhachhangLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblquanlykhachhang)
                .addGap(14, 14, 14))
        );

        jpnthongke.setBackground(new java.awt.Color(0, 153, 0));
        jpnthongke.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnthongke.setForeground(new java.awt.Color(255, 255, 255));

        lblthongke.setIcon(new javax.swing.ImageIcon(dir+"\\thongke.png"));
        lblthongke.setForeground(new java.awt.Color(255, 255, 255));
        lblthongke.setText("Thống Kê Doanh Số");

        javax.swing.GroupLayout jpnthongkeLayout = new javax.swing.GroupLayout(jpnthongke);
        jpnthongke.setLayout(jpnthongkeLayout);
        jpnthongkeLayout.setHorizontalGroup(
            jpnthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnthongkeLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblthongke)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jpnthongkeLayout.setVerticalGroup(
            jpnthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnthongkeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblthongke)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenuLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnthongke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnquanlynhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnquanlykhachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnqldonhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jpnqldonhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnquanlykhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnquanlynhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jpnthongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnview.setBackground(new java.awt.Color(179, 179, 179));

        javax.swing.GroupLayout jpnviewLayout = new javax.swing.GroupLayout(jpnview);
        jpnview.setLayout(jpnviewLayout);
        jpnviewLayout.setHorizontalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        jpnviewLayout.setVerticalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnrootLayout = new javax.swing.GroupLayout(jpnroot);
        jpnroot.setLayout(jpnrootLayout);
        jpnrootLayout.setHorizontalGroup(
            jpnrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnrootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jpnrootLayout.setVerticalGroup(
            jpnrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnrootLayout.createSequentialGroup()
                .addComponent(jpnview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnroot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnroot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnqldonhang;
    private javax.swing.JPanel jpnquanlykhachhang;
    private javax.swing.JPanel jpnquanlynhanvien;
    private javax.swing.JPanel jpnroot;
    private javax.swing.JPanel jpnthongke;
    private javax.swing.JPanel jpnview;
    private javax.swing.JLabel lblqldonhang;
    private javax.swing.JLabel lblquanlykhachhang;
    private javax.swing.JLabel lblquanlynhanvien;
    private javax.swing.JLabel lblthongke;
    // End of variables declaration//GEN-END:variables
}
