/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Quanly;

import domainmodels.KhachHang;
import iservices.IKhachHangService;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.KhachHangService;

/**
 *
 * @author ADMIN
 */
public class JplKhachHang extends javax.swing.JPanel {

    private IKhachHangService iKhachHangService = new KhachHangService();
    DefaultTableModel moDel = new DefaultTableModel();

    public JplKhachHang() {
        initComponents();
        loadDataKhachHang(iKhachHangService.getAll());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnSuakh = new javax.swing.JButton();
        btnMoikh = new javax.swing.JButton();
        btnThemkh = new javax.swing.JButton();
        btnXoakh = new javax.swing.JButton();
        txtMakh = new javax.swing.JTextField();
        txtTenkh = new javax.swing.JTextField();
        txtTenDemkh = new javax.swing.JTextField();
        txtHokh = new javax.swing.JTextField();
        txtNgaySinhkh = new javax.swing.JTextField();
        txtSdtkh = new javax.swing.JTextField();
        txtThanhPhokh = new javax.swing.JTextField();
        txtDiaChikh = new javax.swing.JTextField();
        txtQuocGiakh = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachhang = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        jTextField34 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnTangkh = new javax.swing.JButton();
        btnGiamkh = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 230, 234));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel14.setText("Mã");

        jLabel15.setText("Tên");

        jLabel16.setText("Tên đệm");

        jLabel17.setText("Họ");

        jLabel18.setText("Ngày sinh");

        jLabel19.setText("SDT");

        jLabel20.setText("Địa chỉ");

        jLabel21.setText("Số lần mua");

        jLabel22.setText("Email");

        btnSuakh.setBackground(new java.awt.Color(255, 51, 0));
        btnSuakh.setForeground(new java.awt.Color(255, 255, 255));
        btnSuakh.setText("Sửa");
        btnSuakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuakhActionPerformed(evt);
            }
        });

        btnMoikh.setBackground(new java.awt.Color(255, 51, 0));
        btnMoikh.setForeground(new java.awt.Color(255, 255, 255));
        btnMoikh.setText("Mới");
        btnMoikh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoikhActionPerformed(evt);
            }
        });

        btnThemkh.setBackground(new java.awt.Color(255, 51, 0));
        btnThemkh.setForeground(new java.awt.Color(255, 255, 255));
        btnThemkh.setText("Thêm");
        btnThemkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemkhActionPerformed(evt);
            }
        });

        btnXoakh.setBackground(new java.awt.Color(255, 51, 0));
        btnXoakh.setForeground(new java.awt.Color(255, 255, 255));
        btnXoakh.setText("Xoá");
        btnXoakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoakhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoakh)
                    .addComponent(btnThemkh)
                    .addComponent(btnMoikh)
                    .addComponent(btnSuakh))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMoikh, btnSuakh, btnThemkh, btnXoakh});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnMoikh)
                .addGap(18, 18, 18)
                .addComponent(btnThemkh)
                .addGap(18, 18, 18)
                .addComponent(btnSuakh)
                .addGap(26, 26, 26)
                .addComponent(btnXoakh)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMoikh, btnSuakh, btnThemkh, btnXoakh});

        txtMakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMakhActionPerformed(evt);
            }
        });

        txtThanhPhokh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThanhPhokhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSdtkh))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHokh, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenDemkh)
                            .addComponent(txtDiaChikh)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNgaySinhkh, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThanhPhokh))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenkh))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuocGiakh, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel14, jLabel15, jLabel16, jLabel17, jLabel18, jLabel19, jLabel20, jLabel21, jLabel22});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgaySinhkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(txtQuocGiakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtHokh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtTenDemkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtSdtkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtDiaChikh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThanhPhokh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(99, 99, 99))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel14, jLabel15, jLabel16, jLabel17, jLabel18, jLabel19, jLabel20, jLabel21, jLabel22, txtDiaChikh, txtHokh, txtMakh, txtNgaySinhkh, txtQuocGiakh, txtSdtkh, txtTenDemkh, txtTenkh, txtThanhPhokh});

        tblKhachhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Tên đệm", "Họ", "Email", "Ngày sinh", "Sdt", "Địa chỉ", "Số lần mua"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachhang.setGridColor(new java.awt.Color(47, 85, 212));
        tblKhachhang.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblKhachhang.setShowGrid(true);
        tblKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachhang);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tra cứu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel43.setText("Tên:");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addContainerGap())
        );

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel44.setText("Giới tính");

        jLabel45.setText("Chức vụ");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel44)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Sắp xếp theo tên");

        btnTangkh.setBackground(new java.awt.Color(255, 51, 0));
        btnTangkh.setForeground(new java.awt.Color(255, 255, 255));
        btnTangkh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-sort-alpha-up-reversed-20.png"))); // NOI18N
        btnTangkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangkhActionPerformed(evt);
            }
        });

        btnGiamkh.setBackground(new java.awt.Color(255, 51, 0));
        btnGiamkh.setForeground(new java.awt.Color(255, 255, 255));
        btnGiamkh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-sort-alpha-up-20.png"))); // NOI18N
        btnGiamkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamkhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(39, 39, 39)
                        .addComponent(btnTangkh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGiamkh)
                        .addGap(13, 13, 13))
                    .addComponent(jScrollPane1))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnGiamkh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(btnTangkh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuakhActionPerformed
        try {
            if (checkValidate()) {
                String ma = txtMakh.getText();
                String ten = txtTenkh.getText();
                String tenDem = txtTenDemkh.getText();
                String ho = txtHokh.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Date ngaySinh = (Date) sdf.parse(txtNgaySinhkh.getText());
                String sdt = txtSdtkh.getText();
                String diachi = txtDiaChikh.getText();
                String thanhpho = txtThanhPhokh.getText();
                String quocgia = txtQuocGiakh.getText();

                KhachHang khachHang = new KhachHang();
                khachHang.setMa(ma);
                khachHang.setTen(ten);
                khachHang.setTenDem(tenDem);
                khachHang.setHo(ho);
                khachHang.setNgaySinh(ngaySinh);
                khachHang.setSdt(sdt);
                khachHang.setDiaChi(diachi);      

                iKhachHangService.sua(khachHang);
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                clearForm();
                loadDataKhachHang(iKhachHangService.getAll());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSuakhActionPerformed
    private void clearForm() {
        txtMakh.setText("");
        txtTenkh.setText("");
        txtTenDemkh.setText("");
        txtHokh.setText("");
        txtNgaySinhkh.setText("");
        txtSdtkh.setText("");
        txtDiaChikh.setText("");
        txtThanhPhokh.setText("");
        txtQuocGiakh.setText("");
        tblKhachhang.clearSelection();
    }

    private void loadDataKhachHang(List<KhachHang> listKhachHangView) {
        moDel = new DefaultTableModel();
        moDel = (DefaultTableModel) tblKhachhang.getModel();
        moDel.setRowCount(0);
        for (KhachHang khachHang : listKhachHangView) {
            moDel.addRow(new Object[]{
                khachHang.getMa(),
                khachHang.getTen(),
                khachHang.getTenDem(),
                khachHang.getHo(),
                khachHang.getNgaySinh(),
                khachHang.getSdt(),
                khachHang.getDiaChi(),
                khachHang.getNgayTao(),
                khachHang.getNgaySua(),});
        }
    }
    private void btnMoikhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoikhActionPerformed
        clearForm();
    }//GEN-LAST:event_btnMoikhActionPerformed

    private void btnThemkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemkhActionPerformed
        try {
            if (checkValidate()) {
                String ma = txtMakh.getText();
                if (iKhachHangService.checkTrungMa(ma) != null) {
                    JOptionPane.showMessageDialog(this, "Mã đã tồn tại, nhập mã khác");
                    return;
                }
                String ten = txtTenkh.getText();
                String tenDem = txtTenDemkh.getText();
                String ho = txtHokh.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Date ngaySinh = (Date) sdf.parse(txtNgaySinhkh.getText());
                String sdt = txtSdtkh.getText();
                String diachi = txtDiaChikh.getText();
                String thanhpho = txtThanhPhokh.getText();
                String quocgia = txtQuocGiakh.getText();
            
                KhachHang khachHang = new KhachHang();
                khachHang.setMa(ma);
                khachHang.setTen(ten);
                khachHang.setTenDem(tenDem);
                khachHang.setHo(ho);
                khachHang.setNgaySinh(ngaySinh);
                khachHang.setSdt(sdt);
                khachHang.setDiaChi(diachi);
      
                
                iKhachHangService.them(khachHang);
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                clearForm();
                loadDataKhachHang(iKhachHangService.getAll());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemkhActionPerformed

    private void btnXoakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoakhActionPerformed
        if (iKhachHangService.getAll().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không còn gì để xoá");
            return;
        }
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá không ?");
        if (hoi != JOptionPane.YES_OPTION) {
            clearForm();
            return;
        } else {
            String ma = txtMakh.getText();
            iKhachHangService.xoa(ma);
            JOptionPane.showMessageDialog(this, "Xoá thành công");
            clearForm();
            loadDataKhachHang(iKhachHangService.getAll());
        }
    }//GEN-LAST:event_btnXoakhActionPerformed

    private void txtThanhPhokhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThanhPhokhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThanhPhokhActionPerformed

    private void tblKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachhangMouseClicked
        int index = tblKhachhang.getSelectedRow();
        txtMakh.setText(tblKhachhang.getValueAt(index, 0).toString());
        txtTenkh.setText(tblKhachhang.getValueAt(index, 1).toString());
        txtTenDemkh.setText(tblKhachhang.getValueAt(index, 2).toString());
        txtHokh.setText(tblKhachhang.getValueAt(index, 3).toString());
        txtNgaySinhkh.setText(tblKhachhang.getValueAt(index, 4).toString());
        txtSdtkh.setText(tblKhachhang.getValueAt(index, 5).toString());
        txtDiaChikh.setText(tblKhachhang.getValueAt(index, 6).toString());
        txtThanhPhokh.setText(tblKhachhang.getValueAt(index, 7).toString());
        txtQuocGiakh.setText(tblKhachhang.getValueAt(index, 8).toString());
      
    }//GEN-LAST:event_tblKhachhangMouseClicked
    private boolean checkValidate() {
        if (utilities.ULHelper.checknull(txtMakh, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtTenkh, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtTenDemkh, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtHokh, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtNgaySinhkh, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checkNgay(txtNgaySinhkh, "Vui lòng nhập đúng định dạng yyyy-MM-dd !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtSdtkh, "Không được để trống !")) {
            return false;
        }

        if (utilities.ULHelper.CheckSDT(txtSdtkh, "Nhập số điện thoại đúng định dạng !")) {
            return false;
        }

        if (utilities.ULHelper.checknull(txtDiaChikh, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtThanhPhokh, "Không được để trống !")) {
            return false;
        }
        if (utilities.ULHelper.checknull(txtQuocGiakh, "Không được để trống !")) {
            return false;
        }

        return true;
    }
    private void btnTangkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangkhActionPerformed
        List<KhachHang> list = iKhachHangService.sapXepTenTang();
        loadDataKhachHang(list);
        JOptionPane.showMessageDialog(this, "Sắp xếp theo tên tăng dần");
    }//GEN-LAST:event_btnTangkhActionPerformed

    private void btnGiamkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamkhActionPerformed
        List<KhachHang> list = iKhachHangService.sapXepTenGiam();
        loadDataKhachHang(list);
        JOptionPane.showMessageDialog(this, "Sắp xếp theo tên giảm dần");
    }//GEN-LAST:event_btnGiamkhActionPerformed

    private void txtMakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMakhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMakhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiamkh;
    private javax.swing.JButton btnMoikh;
    private javax.swing.JButton btnSuakh;
    private javax.swing.JButton btnTangkh;
    private javax.swing.JButton btnThemkh;
    private javax.swing.JButton btnXoakh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTable tblKhachhang;
    private javax.swing.JTextField txtDiaChikh;
    private javax.swing.JTextField txtHokh;
    private javax.swing.JTextField txtMakh;
    private javax.swing.JTextField txtNgaySinhkh;
    private javax.swing.JTextField txtQuocGiakh;
    private javax.swing.JTextField txtSdtkh;
    private javax.swing.JTextField txtTenDemkh;
    private javax.swing.JTextField txtTenkh;
    private javax.swing.JTextField txtThanhPhokh;
    // End of variables declaration//GEN-END:variables
}
